version: "3.6"
services:
  # Application service layer
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_octane
    working_dir: /var/www/html
    volumes:
      - "./src:/var/www/html"
    ports:
      - "9000:9000"
    networks:
     - octane_network

  octane_database:
    container_name: octane_database
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root
      - MYSQL_DATABASE=octane
    volumes:
      - database:/var/lib/mysql
    ports:
      - 3309:3306
    networks:
      - octane_network

volumes:
  database:

networks:
  octane_network:
    external: true